import ffmpeg           # pip3 install ffmpeg-python
import os               # used to find the path of the files
import sys              # used for the arguments
from shutil import copy # used to copy the files that will not be converted to opus that are present

LOSSLESS     = ["wav", "flac", "ape"]   # formats that will be converted to opus. Obviously, only lossless stuff
TARGET       = ".opus"                  # target extension.
BITRATE      = "160k"                   # target bitrate
FOLDER_DELIM = "/"                      # separator between folders

def extract(query):
    """extract informations from the filename + path string of a file, return an object with everything in there"""
    path          = FOLDER_DELIM.join(query.split(FOLDER_DELIM)[:-1])   # path without the filename. if your filenames have the folder delimiter this won't work (not that it needs to?)
    filenameFull  = query.split(FOLDER_DELIM)[-1]                       # filename with the extension
    filename      = '.'.join(filenameFull.split('.')[:-1])              # remove the extension. some files might have other '.' in them, so keep that in mind
    extension     = filenameFull.split('.')[-1]                         # only the extension, without the '.'
    return {"filenameFull":filenameFull, "filename":filename, "path":path, "extension":extension}

def find(query):
    """return all the files (not directories) in a folder, including what is in subfolders"""
    acc = []
    for root, dirs, files in os.walk(query, topdown=False):
        for name in files:
            acc += [os.path.join(root, name)]
    return acc

def makeOutputPath(outputPath, filePath, filename):
    """for a given file, give an output path. Eventually create missing folders so ffmpeg doesn't error out"""
    if filePath == "" or filePath == None:
        return None
    if outputPath[-1] == FOLDER_DELIM: # remove an eventual / at the end
        outputPath = outputPath[:-1]

    fullPath = outputPath + FOLDER_DELIM + filePath
    fullPath += FOLDER_DELIM            # add a '/' at the end of the path

    if not os.path.isfile(fullPath):    # if the path doesn't exist, create it!
        try:
            os.makedirs(fullPath)
        except FileExistsError:
            pass    # nothing really went wrong if the folder already exists, continue quietly
    return fullPath + filename + TARGET # return the path and target filename

def treat(input, output):
    """for a given input folder and output folder, return an array of file objects as generated by extract(), with an output path attribute argument so everything can just be passed to ffmpeg"""
    files = find(input)
    acc = []
    for file in files:
        fileInfo = extract(file)
        out = makeOutputPath(output, fileInfo["path"], fileInfo["filename"])
        if not out == None:
            fileInfo["outPath"] = out
            acc += [fileInfo]
    return acc

def convert(fileDict):
    """convert all files of the desired formats to opus, copy the rest. Takes an array of file objects as made by extract, with the additional output path attribute in, nothing out"""
    for fileInfo in fileDict:
        inFile  = fileInfo["path"] + FOLDER_DELIM + fileInfo["filenameFull"]
        outFile = fileInfo["outPath"]
        if fileInfo["extension"] in LOSSLESS:
            try:
                if not os.path.isfile(outFile):
                    print("[Converting]\t" + inFile)
                    ffmpeg.input(inFile).output(outFile, audio_bitrate=BITRATE).global_args('-loglevel', 'error').run()
                else:
                    print("[Skipping]\t" + outFile)
            except:
                print("[Error][Converting]\t" + inFile)
        else:
            try:
                print("[Copying]\t" + inFile)
                copy(inFile, FOLDER_DELIM.join(outFile.split(FOLDER_DELIM)[:-1]))
            except:
                print("[Error][Copying]\t" + inFile)

def run(arguments):
    """arguments: array of arguments as given by sys.argv minus the program name that would be at position 0"""
    if len(arguments) < 2:
        print("Not enough arguments: need input and output dir!")
        return None
    input  = arguments[0]
    output = arguments[1]
    print("[INPUT]\t\t" + input)
    print("[OUTPUT]\t" + output)
    print("[TARGET]\t" + TARGET)
    print("[BITRATE]\t" + BITRATE)
    print("[FORMATS]\t" + ', '.join(LOSSLESS) + "\n")
    fileDict = treat(input, output)
    convert(fileDict)

run(sys.argv[1:])
